modLoader = "javafml"
loaderVersion = "[36.2.0,)"
license = "GNU GPLv3"
issueTrackerURL = "https://github.com/HelloCrossy/WondersOfTheWorld/issues"

[[mods]]
modId = "wondersoftheworld"
version = "${file.jarVersion}"
displayName = "ZAWA: Wonders Of The World"
#updateJSONURL=""
displayURL = "https://www.curseforge.com/minecraft/mc-mods/wonders-of-the-world"
logoFile = "logo.png"
credits = "Devs: HelloCrossy67, heavy808s, SpiggitySpag, Arty, Platinum, chilotic, PumpkinedPatch     Other: Shoresy, Fisk, Mnesikos, ClimbableChunky,"
authors = "HelloCrossy67"
description = '''
Wonders of the World is an addon mod for ZAWA Evolved, on MC JAVA version 1.16.5. This mod adds a total of 25 animals, with multiple species of some of these entities AND a total of 5 plushies! The mod is of the ZAWA Style and follows their guidelines relatively closely. A big thanks to our team, the ZAWA Devs: Fisk & Mnesikos, aswell as our amazing sponsor Shoresy! Stay tuned for future updates, along with more plushies!'''

[[dependencies.wondersoftheworld]]
modId = "forge"
mandatory = true
versionRange = "[36.2.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wondersoftheworld]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wondersoftheworld]]
modId = "zawa"
mandatory = true
versionRange = "[1.16.5-1.0.2-BeefBeta-TropicalExpedition3,)"
ordering = "AFTER"
side = "BOTH"